language: csharp
dist: xenial
sudo: required
dotnet: 2.1.302
mono: none
script:
  - dotnet restore
  - dotnet build --configuration Release --no-restore --version-suffix $TRAVIS_BUILD_NUMBER
  - dotnet pack source/ --configuration Release --no-build --version-suffix $TRAVIS_BUILD_NUMBER
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push source/*/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  on:
    condition: $TRAVIS_BRANCH = master
notifications:
  email:
    on_success: never
    on_failure: always
